Repository Data-Simply/pyretailscience, pull requests merged in 2024-09, with the labels that each got.

#80 docs: updated analysis module docs
  docs/analysis_modules.md
  docs/assets/images/analysis_modules/customer_decision_hierarchy.svg
  docs/assets/images/analysis_modules/index_plot.svg
  pyretailscience/standard_graphs.py
Labels: documentation, Review effort [1-5]: 2

#81 fix: dependabot jupyerlab security update
  poetry.lock
  pyproject.toml
Labels: dependencies, Review effort [1-5]: 1

#84 feat: add line plot
  docs/analysis_modules.md
  docs/api/plots/line.md
  docs/assets/images/analysis_modules/plots/line_plot.svg
  mkdocs.yml
  poetry.lock
  pyproject.toml
  pyretailscience/plots/__init__.py
  pyretailscience/plots/line.py
  pyretailscience/style/graph_utils.py
  pyretailscience/style/tailwind.py
  tests/plots/__init__.py
  tests/plots/test_line.py
Labels: documentation, enhancement, Review effort [1-5]: 4
