Repository Data-Simply/pyretailscience, pull requests merged in 2025-02, with the labels that each got.

#88 feat: revenue tree
  data/transactions.parquet
  docs/analysis_modules.md
  docs/api/revenue_tree.md
  docs/assets/images/analysis_modules/revenue_tree.svg
  docs/examples/revenue_tree.ipynb
  mkdocs.yml
  poetry.lock
  pyproject.toml
  pyretailscience/options.py
  pyretailscience/revenue_tree.py
  tests/test_revenue_tree.py
Labels: Review effort [1-5]: 4, Possible security concern

#89 feat: changed threshold seg to use ibis
  docs/examples/segmentation.ipynb
  poetry.lock
  pyproject.toml
  pyretailscience/segmentation.py
  tests/test_segmentation.py
Labels: Review effort [1-5]: 3

#93 Feature/refactor standard graph plots
  .github/workflows/gh-page.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/analysis_modules.md
  poetry.lock
  pyproject.toml
  pyretailscience/plots/index.py
  pyretailscience/plots/time.py
  pyretailscience/plots/waterfall.py
  pyretailscience/standard_graphs.py
  pyretailscience/style/graph_utils.py
  tests/plots/test_index.py
  tests/plots/test_time.py
  tests/plots/test_waterfall.py
  tests/test_standard_graphs.py
  uv.lock
Labels: Review effort [1-5]: 4

#94 fix: mkdocs issue
  .github/workflows/gh-page.yml
  docs/api/plots/index.md
  docs/api/plots/time.md
  docs/api/plots/waterfall.md
  docs/api/standard_graphs.md
Labels: Review effort [1-5]: 1

#95 refactor with ibis
  pyretailscience/plots/index.py
  tests/plots/test_index.py
Labels: Review effort 4/5

#97 Refactor revenue tree
  pyretailscience/revenue_tree.py
  tests/test_revenue_tree.py
Labels: Review effort 3/5

#98 version bump
  .github/workflows/release.yml
Labels: Review effort 4/5

#99 bump version
  .github/workflows/release.yml
Labels: Review effort 2/5

#101 version bump
  .github/workflows/release.yml
Labels: Review effort 2/5

#102 version bump
  .github/workflows/release.yml
  uv.lock
Labels: Review effort 2/5

#103 version bump
  .github/workflows/release.yml
  uv.lock
Labels: Review effort 2/5

#104 version bump
  .github/workflows/release.yml
Labels: Review effort 2/5

#105 version bump
  .github/workflows/release.yml
  uv.lock
Labels: Review effort 2/5

#106 version bump
  .github/workflows/release.yml
  uv.lock
Labels: Review effort 2/5

#107 version bump
  .github/workflows/release.yml
Labels: Review effort 2/5

#109 chore: update ruff and format pyproject.toml
  pyproject.toml
  uv.lock
Labels: Review effort 1/5

#111 Added threshold segmentation analysis modules docs
  docs/analysis_modules.md
  docs/assets/images/analysis_modules/threshold_segmentation.svg
Labels: Review effort 1/5
