Repository Data-Simply/pyretailscience, pull requests merged in 2025-03, with the labels that each got.

#142 product association
  pyretailscience/analysis/product_association.py
Labels: Review effort 1/5

#145 mkdocs
  mkdocs.yml
Labels: Review effort 1/5

#146 Ibis upgrade
  pyproject.toml
  uv.lock
Labels: Review effort 1/5

#149 product association
  pyretailscience/analysis/product_association.py
  tests/analysis/test_product_association.py
Labels: Review effort 2/5

#153 Seg-Transaction-Stats
  pyretailscience/analysis/segmentation.py
  tests/analysis/test_segmentation.py
  uv.lock
Labels: Review effort 2/5

#155 python version updated
  pyproject.toml
  tests/style/test_graph_utils.py
  uv.lock
Labels: Review effort 1/5

#165 feat: add new columns to options to support upcoming functionality
  .pre-commit-config.yaml
  options_template.toml
  pyretailscience/options.py
  tests/test_options.py
  tests/toml_files/test_options.toml
Labels: Review effort 2/5

#158 add elasticity revenue tree
  .gitignore
  options_template.toml
  pyretailscience/analysis/revenue_tree.py
  pyretailscience/options.py
  tests/analysis/test_revenue_tree.py
  tests/test_options.py
  tests/toml_files/test_options.toml
Labels: Review effort 3/5
